require "plugins"
require "options"
require "keymaps"

require "plugins/lsp"
require "plugins/completion"
require "plugins/telescope"
require "plugins/treesitter"
require "plugins/lualine"
require "plugins/lspsaga"
